name: chatd
version: 0.1.0.0
github: "githubuser/chatd"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/chatd#readme>

dependencies:
  - base 
  - mtl 
  - network 
  - websockets 
  - text 

library:
  source-dirs: src
  exposed-modules:
    - ChatClient
    - ChatServer

executables:
  chatd-server:
    main: Main.hs
    source-dirs: app/server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chatd
  chatd-client:
    main: Main.hs
    source-dirs: app/client
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chatd

tests:
  chatd-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chatd
